version: "3"

services:
  postgresql:
    container_name: "postgresql"
    image: postgres:15
    restart: always
    env_file:
      - ./.env
    volumes:
      - ./postgres-data:/var/lib/postgresql/data/


  backend:
    container_name: "backend"
    build: .
    command: python -m app
    restart: always
    env_file:
      - ./.env
    ports:
      - 8000:8000


volumes:
  postgres-data:
